name: Rust

on:
    push:
        branches: ["main"]
        paths:
            - "src/**"
            - "Cargo.lock"
            - "Cargo.toml"
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
            - name: Build
              run: cargo build --verbose
            - name: Cache rust
              uses: Swatinem/rust-cache@v2
            - name: Run tests
              run: cargo test --verbose
