name: Rust

on:
    push:
        branches: ["dev"]
        paths:
            - "src/**"
            - "Cargo.lock"
            - "Cargo.toml"
    pull_request:
        branches: ["dev"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
            - name: Build
              run: cargo build --verbose
            - name: Cache rust
              uses: Swatinem/rust-cache@v2
            - name: Run tests
              run: cargo test --verbose
